# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
    #Rodar Yarn e instalar as dependencias(Para buildar)
    - name: Install Deps
      run: yarn
    #Rodar yarn build e buildar
    - name: Run Build
      run: yarn build
    
    - name: copy Dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "~/app/node-deploy"
      
    #Rodar Yarn
    #Executar a Build
    #Copiar pasta Dist para dentro da vps
    #substituir o codigo existente para o novo codigo 
    #rodar Yarn na DO
    #executar as migrations
    #restartar o servidor node

